excluded:
  - Carthage
  - ThirdParty
  - fastlane
  - vendor
force_cast: warning # implicitly
line_length: 140
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200
identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - key
    - url
    - upc
    - app
    - egg
    - rgb
    - top
